### ISSUE TITLE
Actualizar las lista de skills de UX (Especialización)

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/rubric#10]
Actualmente solo se tiene considerado dos skills en `UX` que estan evaluados dentro del `CC`, ahora que ya hay el track de especialización hay mas skills ha evaluar para el mismo.
[Rubric](https://docs.google.com/spreadsheets/d/1Tviny8HzskBKP0HDKXoSClqyHsvQTO0XsWnyKWZGvJA/edit#gid=396924353)

cc/ @diegovelezg   @lalogf  :eyes:

**Comment by lalogf** [comment]
Hola @MaiaRojas , acabo de agregar los niveles esperados para el final del track en el spreadsheet.

**Comment by lupomontero** [comment]
Esto ya está listo y pronto saldrá en el release `v2.2.0`... :rocket: :stars: 

Ver https://github.com/Laboratoria/rubric/commit/bb4257797fa199bea47e352ac50551485653e2da
