### ISSUE TITLE
Parametros con valores por defectos ultimos

### ISSUE THREAD

**Issue by corosteg** [Laboratoria/rubric#5]
Segun lo que entiendo los parametros con valores por defecto tienen que estar posicionado al final para no tener que definirlos. Hay una razon por cual estan posicionado al inicio?

linea 8: ` buildTree = (nodes = categories, parent)`
linea 31: `const buildTreeWithLocale = (locale = 'es', nodes = categories, parent)`

**Comment by lupomontero** [comment]
Ahora que estoy revisando este repo otra vez, creo que tienes razón con respecto al orden de los argumentos... :thinking: ... creo que he cambiado de opinión. El problema es que esto sería un **breaking change** ya que cambia la API pública del módulo. Antes de proceder con esto me gustaría entender bien quienes están usando el módulo `rubric`, dónde y cómo para comunicar los cambios y apoyar con los upgrades si fuera necesario.

- [ ] [curriculum-parser](https://github.com/Laboratoria/curriculum-parser)
- [ ] LMS?
- [ ] ...???

cc/ @Laboratoria/product-developers

**Comment by MaiaRojas** [comment]
En el `lms` aun no lo hemos implementado, pero lo tenemos en mapa para los siguientes sprints
