### ISSUE TITLE
Cambiar orden de habilidades

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/rubric#7]
Segun la ui  de feature-feedback  tiene mas sentido que *UX* este antes que *Soft*, por  eso solicito eso cambios.

*Actual*
```js   
  "soft": {
    "order": 2
  },
  "ux": {
    "order": 3
  }
```
*Propuesta* 

```js   
 "soft": {
   "order": 3
  },
  "ux": {
    "order": 2
  }
```

**Comment by lupomontero** [comment]
Gracias por el feedback @MaiaRojas!

Esto ya está implementado en https://github.com/lupomontero/rubric/commit/f5db012c833bc20b7e940d8834b69198a6e91fd0 y se incluirá en el próximo release (`v2.1.0`) en las próximas horas :wink:
